version: '3'

services:
  tsc:
    image: startprojekt/treneris-tsc
    container_name: "tsc"
    networks:
      - treneris_network
    ports:
      - "8003:80"
#  tsb:
#    image: startprojekt/treneris-tsb
#    container_name: "tsb"
#    ports:
#      - "8002:80"
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/include:/etc/nginx/include
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - treneris_network
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  treneris_network:
    external: true
